### PR TITLE
Full code for the sprint, just needs a few changes.

### PR DESCRIPTION
**Pull request by chrisplmmr**
Full code for the sprint, just needs a few changes.

### CODE REVIEW

**Review by rshah918 — APPROVED** [review]

**Comment by rshah918** [comment]
Nice job following the coding standards! The comments are wonderful and variable name's follow the standard

**Review by andrehrz — APPROVED** [review]
Great work, good job as leaving ruby code out of the views!

**Comment by chrisplmmr** [comment]
Lots of comments. Good variable names. Class names and variable names follow coding standard. Good indentations and keeping files organized. Instance variables start with @.

**Comment by ilianaagui711** [comment]
Very good use of comments and variable names! Also, very good use of nested resources and routes.

**Pull request merged**
